### ISSUE TITLE
Installation error on android

### ISSUE THREAD

**Issue by losheredos** [dpa99c/react-native-launch-navigator#11]
- [ x ] bug report

I installed the package as described but I get native errors such as:

> 
> error: package uk.co.workingedge.RNLaunchNavigator does not exist
> import uk.co.workingedge.RNLaunchNavigator.RNLaunchNavigatorPackage;
> 
> error: cannot find symbol
>           new RNLaunchNavigatorPackage(),

- React Native version 
   55.4

- Other React Native modules/components/tools
"dependencies": {
    "axios": "^0.18.0",
    "cross-os": "^1.3.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-calendars": "^1.22.0",
    "react-native-image-picker": "^0.28.0",
    "react-native-launch-navigator": "^1.0.5",
    "react-native-maps": "^0.23.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-svg": "^9.3.7",
    "react-native-svg-uri": "^1.2.3",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1"
  },

- Dev machine OS and version, e.g.
    - Windows 10
  
- Device details
    Google nexus 5 simulator

- OS details
    Android 5.0
	
- Node JS version
   v8.11.2

- Target Android SDK version
22

**Comment by dpa99c** [comment]
Please try the [example project](https://github.com/dpa99c/react-native-launch-navigator-example) and confirm if you can see the same error. It works fine for me.

**Comment by losheredos** [comment]
I tried to install the package again and now it worked without any problem.. Maybe automated linking had some issues I guess, this time I did all manually by looking at your example project. Anyways, thank you for this nice package!
