### ISSUE TITLE
In iOS fatal error while building: React/RCTEventEmitter.h and React/RCTBridgeModule file not found

### ISSUE THREAD

**Issue by leonardosoares1** [dpa99c/react-native-launch-navigator#15]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
error fatal while building app in a iOS

**Expected behavior:**
Build success with react-native-launch-navigation

**Steps to reproduce:**
- react-native init AwesomeExample --version react-native@0.60.4
- yarn add react-native-launch-navigator
- react-native run-ios

**Environment information**

- React Native version
	-  0.60.4
- Other React Native modules/components/tools
"dependencies": {
    "@react-native-community/geolocation": "^1.4.2",
    "axios": "^0.19.0",
    "formik": "^1.5.8",
    "immer": "^3.1.3",
    "lodash": "^4.17.15",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-fbsdk": "1.0.0-rc.5",
    "react-native-flash-message": "^0.1.13",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-launch-navigator": "^1.0.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-progress": "^3.6.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-shimmer-placeholder": "^1.0.35",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-view": "^2.9.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "reactotron-react-native": "^3.6.4",
    "reactotron-redux": "^3.1.1",
    "reactotron-redux-saga": "^4.2.2",
    "redux": "^4.0.4",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.5",
    "styled-components": "^4.3.2",
    "yup": "^0.27.0"
  },
 "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-eslint": "^10.0.2",
    "babel-jest": "^24.8.0",
    "babel-plugin-root-import": "^6.3.0",
    "eslint": "^6.0.1",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-import-resolver-babel-plugin-root-import": "^1.1.1",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "eslint-plugin-react-native": "^3.7.0",
    "jest": "^24.8.0",
    "jetifier": "^1.6.3",
    "metro-react-native-babel-preset": "^0.55.0",
    "prettier": "^1.18.2",
    "react-test-renderer": "16.8.6"
  }

- Dev machine OS and version, e.g.
    - OSX
        - ProductVersion: 10.14.6
        - BuildVersion: 18G84
        
_Runtime issue_
- Device details
    - iPhone X Simulator
- OS details
    -  12.4	
	
_iOS build issue:_
- Node JS version
    - 12.3.1
- XCode version
    - 10.3

**Related code:**
```
import LaunchNavigator from 'react-native-launch-navigator';

if (Platform.OS === 'android') {
      LaunchNavigator.setGoogleApiKey(
        'API-KEY'
      );
    }
    LaunchNavigator.navigate([
      infoStore.address.latitude,
      infoStore.address.longitude,
    ]);
```

**Console output**
```
.../node_modules/react-native-launch-navigator/ios/RNLaunchNavigator/WE_ReactNativeLogger.h:2:9: fatal error: 'React/RCTEventEmitter.h' file not found

#import <React/RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1
 error
 generated

.../node_modules/react-native-launch-navigator/ios/RNLaunchNavigator/RNLaunchNavigator.h:1:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>

```
**Other information:**
In version 0.60+ I need exec command 'pod install' into a ios folder, but when I exec code return this message :

```
[!] use_native_modules! skipped the react-native dependency 'react-native-launch-navigator'. No podspec file was found.
```

**Comment by lironsher** [comment]
I have the same issue

**Comment by dpa99c** [comment]
`react-native@0.60.x` support has been added in `react-native-launch-navigator@1.0.6`
