### ISSUE TITLE
uses-sdk:minSdkVersion 4 cannot be smaller than version 16 declared in library

### ISSUE THREAD

**Issue by bencergazda** [dpa99c/react-native-launch-navigator#17]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

**Expected behavior:**

Syncing RN 0.59.9 project with `react-native-launch-navigator` installed should be finished without errors in Android Studio.

**Steps to reproduce:**

`$ react-native init RNLaunchNavigatorTest --version react-native@0.59.9`
`$ yarn add react-native-launch-navigator`
`$ react-native link react-native-launch-navigator`

Start Android Studio, syncing project will fail with

```
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 4 cannot be smaller than version 16 declared in library [com.facebook.react:react-native:0.59.9] /Users/[username]/.gradle/caches/transforms-2/files-2.1/f7c6d642ca74fe7147a17e4bf4e07c33/AndroidManifest.xml as the library might be using APIs not available in 4
	Suggestion: use a compatible library with a minSdk of at most 4,
		or increase this project's minSdk version to at least 16,
		or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```

**Environment information**

- React Native version
	- 0.59.9
- Other React Native modules/components/tools
```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-launch-navigator": "1.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.3"
  },
```
- Dev machine OS and version, e.g.
    - OSX
        - MacOS 10.14.6
	
_Android build issue:_	
- Node JS version
    - v11.10.0
- Gradle version
	- 3.4.2
- Target Android SDK version
	-  28

**Other information:**

**Comment by dpa99c** [comment]
Fixed by #18
