### ISSUE TITLE
IOS - Native module cannot be null

### ISSUE THREAD

**Issue by losheredos** [dpa99c/react-native-launch-navigator#19]
# Bug report

**Current behavior:**
I just installed package, it works fine is android but in ios I get this error..

**Steps to reproduce:**
I just installed, didnt do linking (but actually I tried it before but explaining for this time) and my app builded successfully but I get this error.

**Environment information**
Macbook 2012

Device
  iPhone 5s Simulator

- Node JS version
v8.12.0

- XCode version
10.1

Error details
I just get this error when I call this package by importing it, if I dont import its not showing this error

> Native event module cannot be null.
> new NativeEventEmitter
> NativeEventEmitter.js:36:6
> new RNlogger
> index.js: 386:5
> ..... ... ..

package.json

> "dependencies": {
>     "@react-native-community/async-storage": "^1.6.1",
>     "@react-native-community/geolocation": "^1.4.2",
>     "axios": "^0.19.0",
>     "react": "16.8.6",
>     "react-native": "0.60.4",
>     "react-native-calendars": "^1.200.0",
>     "react-native-google-places-autocomplete": "^1.3.9",
>     "react-native-image-picker": "^1.0.2",
>     "react-native-launch-navigator": "^1.0.6",
>     "react-native-maps": "0.25.0",
>     "react-native-router-flux": "^4.0.6",
>     "react-native-swiper": "^1.5.14",
>     "react-native-webview": "^5.12.1",
>     "react-redux": "^7.1.0",
>     "redux": "^4.0.4"
>   },

Podfile

> platform :ios, '9.0'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> target 'Camp24' do
>   # Pods for Camp24
>   pod 'React', :path => '../node_modules/react-native/'
>   pod 'React-Core', :path => '../node_modules/react-native/React'
>   pod 'React-DevSupport', :path => '../node_modules/react-native/React'
>   pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
>   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
>   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
>   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
>   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
>   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
>   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
>   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
>   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
>   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
>   pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
> 
>   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
>   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
>   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
>   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
>   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
> 
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> 
>   pod 'react-native-webview', :path => '../node_modules/react-native-webview'
> 
>   pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
> 
>   pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
> 
> 
>   pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
> 
> 
>   pod 'react-native-maps', :path => '../node_modules/react-native-maps'
> 
> end
> 

Hope you can help me to fix it, I need it to be working ASAP :(

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/react-native-launch-navigator-example) to see if you can replicate the issue in a control environment.

**Comment by losheredos** [comment]
ok let me check, before that i will add my package.json maybe some packages could making conflicts? or something wrong about pod file

**Comment by losheredos** [comment]
@dpa99c example worked fine, do you think why it happens in my project? :/

**Comment by dpa99c** [comment]
This is specific to your project so unfortunately I can't help you
