### ISSUE TITLE
Remove automatic linking on install/uninstall hooks

### ISSUE THREAD

**Issue by jariwalabhavesh** [dpa99c/react-native-launch-navigator#2]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
react-native-launch-navigation is an awesome library and it is linking itself on npm install that is great as well (That's awesome work to get raid of manual linking). But I am facing some real-world development issue.

1. Generally while working on react-native, developers used to commit native library linking changes to the repo so the other developer need not worry about linking already install libraries. (I used to follow it because every time doing a react-native link, it's risky, In some case, it's breaking the application and also some library needs manual steps for linking, either in android or ios due to some constraint)

2. Most important when we are using auto build servers which build a react-native app and create release builds. This server generally taking a pull of application and then do npm install then build it.
here it will break it because we have already linked changes in file and react-native-launch-navigator will add one more time linking changes and it will appear twice in native files.

It will break app by providing error I had attached screenshot.

![screenshot_1537509776](https://user-images.githubusercontent.com/10993666/45863086-3c56da80-bd92-11e8-8150-a79f745c5f88.png)

**Expected behavior:**
It should work on a react-native link(not automatically on npm install) so it will fix the problem.

This what I thought. What you say let me know...

**Comment by jariwalabhavesh** [comment]
@dpa99c : Awesome Idea 👍

**Comment by dpa99c** [comment]
This should be resolved in v1.0.2 which checks if module is already linked before attempting linking/unlinking.

**Comment by jariwalabhavesh** [comment]
@dpa99c :
Awesome thank you

**Comment by GulinSS** [comment]
@dpa99c can we add a way how to disable automatic linking? Something like https://stackoverflow.com/a/50402065? I mean if some environment variable is present do not linking... I need it for a reason.
