### ISSUE TITLE
cannot install the package using NPM or Yarn 

### ISSUE THREAD

**Issue by Matt-Swingvy** [dpa99c/react-native-launch-navigator#21]
```internal/validators.js:107
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object ```

**Comment by dpa99c** [comment]
This is insufficient information to diagnose the issue. Please open a new issue and complete the issue template and give relevant information such as where/
when the error occurs, full stack trace and in this case the absolute path to the project in your environment.
