### ISSUE TITLE
iphone 7 IOS 12.3 Google Maps not working

### ISSUE THREAD

**Issue by orhanoksuzz** [dpa99c/react-native-launch-navigator#24]
iphone 7 real device IOS 12.3 Google Maps does not work even though they are installed.

**Comment by dpa99c** [comment]
What does "does not work" mean? 

That the Google Maps app is not being launched or that the Google Maps app is being launched but is not behaving as expected when it is launched?

**Comment by orhanoksuzz** [comment]
This code block does not open google maps as expected. 
The latest version of google maps is installed on the device.

`let app = null;

   LaunchNavigator.isAppAvailable(LaunchNavigator.APP.GOOGLE_MAPS).then((isGoogleAvailable) => {
    if(isGoogleAvailable){
        app = LaunchNavigator.APP.GOOGLE_MAPS;
    }else{
        console.warn("GOOGLE_MAPS not available - falling back to default navigation app");
    }

    LaunchNavigator.navigate([50.279306, -5.163158], {
         start: "50.342847, -4.749904",
        app: app
    });
        .then(() => console.log("Launched navigator"))
        .catch((err) => console.error("Error launching navigator: "+err));
});`

**Comment by orhanoksuzz** [comment]
@dpa99c   can you help me?

**Comment by dpa99c** [comment]
Try building and running the [example app](https://github.com/dpa99c/react-native-launch-navigator-example) to rule out possible causes in your own project.

**Comment by dpa99c** [comment]
Close due to no response from OP
