### ISSUE TITLE
Let the user selects the app with 'open with' android system menu

### ISSUE THREAD

**Issue by dngconsulting** [dpa99c/react-native-launch-navigator#26]
Hello,

Is there any way to let the user select himself the right map application with the "open with" system menu (specially on Android with intents) instead of proposing in-app list menu ?

Thanks

Sami

**Comment by dpa99c** [comment]
No, I don't believe you can do this - the android "open with" system menu is built-in and responds to certain pre-defined criteria - I don't believe there's a way to throw a bunch of custom app URL schemes at it and use it as a chooser. 
However you could emulate that menu UI in your own Android app if you wanted it to appear more native.
