### ISSUE TITLE
iPhone 7 ios 13.1.3 google schema problem.

### ISSUE THREAD

**Issue by orhanoksuzz** [dpa99c/react-native-launch-navigator#27]
Hi,
The application does not see the google maps schema in iphone 7 and ios 13.1.3 version.
I want to open the desired location with google maps.The screenshots of the current application are attached.

![Image 1](https://user-images.githubusercontent.com/16277060/72280179-cc382c00-3648-11ea-818c-e7eee76c81ac.jpeg)
![Image 2](https://user-images.githubusercontent.com/16277060/72280180-cc382c00-3648-11ea-85ca-7737cf43f0fe.jpeg)
![Image 3](https://user-images.githubusercontent.com/16277060/72280178-cc382c00-3648-11ea-82f7-575e52fd8606.jpeg)

{
  "name": "navigatorslaunch",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "native-base": "^2.13.8",
   
    "react-native-launch-navigator": "git+https://github.com/dpa99c/react-native-launch-navigator.git#dev",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by dpa99c** [comment]
The likely cause of this is that the script which adds the [query schemes from the `package.json`](https://github.com/dpa99c/react-native-launch-navigator/blob/master/package.json#L35) into the Xcode project `*-Info.plist` has failed to run for some reason so the `NSURLScheme` entries are not present in the plist. You can check this in Xcode and add them manually if they are missing.

**Comment by orhanoksuzz** [comment]
> The likely cause of this is that the script which adds the [query schemes from the `package.json`](https://github.com/dpa99c/react-native-launch-navigator/blob/master/package.json#L35) into the Xcode project `*-Info.plist` has failed to run for some reason so the `NSURLScheme` entries are not present in the plist. You can check this in Xcode and add them manually if they are missing.

How to add manually?

**Comment by dpa99c** [comment]
You need to add to the `LSApplicationQueriesSchemes ` key
![Screenshot 2020-01-16 at 11 27 46](https://user-images.githubusercontent.com/2345062/72521496-6ff52800-3853-11ea-8409-edda867b9caf.png)

The postlink hook script should add these automatically so I will test the example project with latest version of React Native to check if there has been a breaking change which has stopped the script from working.

**Comment by orhanoksuzz** [comment]
Thanks.
It works after adding the info.plist file.
`<key>LSApplicationQueriesSchemes</key>
	<array>
	<string>citymapper</string>	
	<string>comgooglemaps</string>
    <string>navigon</string>
    <string>transit</string>
    <string>waze</string>
    <string>yandexnavi</string>
    <string>uber</string>
    <string>tomtomhome</string>
    <string>com.sygic.aura</string>
    <string>here-route</string>
    <string>moovit</string>
    <string>lyft</string>
    <string>mapsme</string>
    <string>cabify</string>
    <string>baidumap</string>
    <string>taxis99</string>
    <string>iosamap</string>
	</array>`

**Comment by hb2708** [comment]
@orhanoksuzz feel free to mark the issue as closed if it's solved for you
