### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by Azshar** [dpa99c/react-native-launch-navigator#28]
Hello, you can add support androidx in this project?

**Comment by dpa99c** [comment]
This module does not use the legacy Android Support Library so there is no need to migrate it to use the replacement AndroidX library.

Therefore it should work fine in Android projects that use either the Android Support Library or AndroidX.

**Comment by dpa99c** [comment]
No, I am wrong, it does use the Android Support Library for [`android.support.annotation.Nullable`](https://github.com/dpa99c/react-native-launch-navigator/blob/master/android/src/main/java/uk/co/workingedge/RNLaunchNavigator/RNUtils.java#L3).

I'll see whether this can be removed entirely otherwise updated to use AndroidX

**Comment by hb2708** [comment]
@dpa99c @Azshar so this is solved or not?

**Comment by dpa99c** [comment]
No it's still [referencing the Android Support Library](https://github.com/dpa99c/react-native-launch-navigator/blob/master/android/src/main/java/uk/co/workingedge/RNLaunchNavigator/RNUtils.java#L3). 

Apologies, I've been busy with other stuff and no longer use this library myself, so it needs some love - PRs welcome.

**Comment by hb2708** [comment]
PR will be there in 2 minutes

**Comment by dpa99c** [comment]
Fixed by #30 (thanks to @hb2708)

**Comment by hb2708** [comment]
@dpa99c can this be released also coz i am in middle of migration to react-native 0.59.x to 0.60.x?

**Comment by dpa99c** [comment]
@hb2708 I think #29 needs resolving first before I can do a release.
I last tested this module with RN v0.60.4 so I think something in 0.61 or 0.62 has caused it to break with those versions.

**Comment by dpa99c** [comment]
You can install it direct off the master branch of this repo in the meantime

**Comment by hb2708** [comment]
You doing that for now Might create a new pr again for #29 when i go to 0.61 / 0.62

**Comment by NeerajNegi** [comment]
Changing the import to `import androidx.annotation.Nullable;` should do.

**Comment by hb2708** [comment]
@NeerajNegi it's solved already and the fix is there on master

**Comment by NeerajNegi** [comment]
But I see that in npm last publish was 6 months ago and this issue was fixed 3 months ago. Is this fix not available in npm ?
