### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mahaboobshaik** [dpa99c/react-native-launch-navigator#29]
When i tried to install i am getting ERR_INVALID_ARG_TYPE error.

$ npm install --save react-native-launch-navigator

> react-native-launch-navigator@1.0.7 postinstall 
          /Library/WebServer/Documents/native//node_modules/react-native-launch-navigator
> node scripts/postinstall.js

internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at Object.<anonymous> (/Library/WebServer/Documents/native/node_modules/react-native-launch-navigator/scripts/ios.link_helpers.js:45:23)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Library/WebServer/Documents/native/node_modules/react-native-launch-navigator/scripts/postinstall.js:3:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm WARN @react-native-community/masked-view@0.1.5 requires a peer of react-native@^0.57 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows@0.41.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-searchable-list@1.1.3 requires a peer of react-native@^0.44.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-drawer@2.3.3 requires a peer of react-native-screens@^1.0.0 || ^1.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-stack@2.0.2 requires a peer of react-native-safe-area-context@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-tabs@2.6.2 requires a peer of react-native-screens@^1.0.0 || ^1.0.0-alpha but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-launch-navigator@1.0.7 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-launch-navigator@1.0.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-02-27T19_22_54_422Z-debug.log

**Comment by vimalraviyadav** [comment]
Am also facing same issue can any one share the solution to resolve this issue

**Comment by hb2708** [comment]
@dpa99c i moved my project to RN 0.60.2 and the react-native-launch-navigator works nicely
@mahaboobshaik & @vimalraviyadav can you guys try it with new plain react native project??  and if still face that issue please share that new project so can take a look at it what is the underlying issue.

**Comment by hb2708** [comment]
Hey @mahaboobshaik & @vimalraviyadav i think this can be closed unless you are still facing this the you can reopen again. It worked for me totally fine on RN 0.60.2

**Comment by hb2708** [comment]
@dpa99c will leave upto you

**Comment by dpa99c** [comment]
Thanks @hb2708, I will close this since no response from OP. If there is an underlying issue, it can be opened as a new issue

**Comment by hb2708** [comment]
@dpa99c Thanks. I guess then can do a small release alsomaybe
