### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by Vilina** [dpa99c/react-native-launch-navigator#3]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
on 
npm install --save react-native-launch-navigator

i get error 
> react-native-launch-navigator@1.0.2 postinstall D:\projects\s-d-app\node_modules\react-native-launch-navigator
> node scripts/postinstall.js

>path.js:28
 >   throw new TypeError('Path must be a string. Received ' + inspect(path));
  >  ^

>TypeError: Path must be a string. Received null
>    at assertPath (path.js:28:11)
>   at Object.join (path.js:489:7)
>    at Object.<anonymous> (D:\projects\s-d-app\node_modules\react-native-launch->navigator\scripts\ios.link_helpers.js:44:23)
>    at Module._compile (module.js:652:30)
>    at Object.Module._extensions..js (module.js:663:10)
>    at Module.load (module.js:565:32)
>    at tryModuleLoad (module.js:505:12)
>    at Function.Module._load (module.js:497:3)
>    at Module.require (module.js:596:17)
>    at require (internal/module.js:11:18)

**Expected behavior:**

**Steps to reproduce:**

**Environment information**
I am developing with expo

- React Native version
	- `react-native --version`
        react-native-cli: 2.0.1
        react-native: 0.55.2
- Other React Native modules/components/tools
	- List `dependencies` and `devDependencies` from `package.json`
        "jest-expo": "^27.0.0",
        "react-native-camera": "^1.3.0",
        "react-native-qrcode-scanner": "^1.1.0"
- Dev machine OS and version, e.g   
    - Windows 10
        - `winver`
        windows 10
- Node JS version
    - `node -v`
    v8.10.0

**Comment by dpa99c** [comment]
Expo does not support native modules such as this:

https://docs.expo.io/versions/latest/introduction/faq

> The most limiting thing about Expo is that you can't add in your own native modules without detaching and using ExpoKit.

**Comment by amalamarypaul** [comment]
error on install
