### ISSUE TITLE
Native picker is not prompt - default app used instead

### ISSUE THREAD

**Issue by GuillaumeNachury** [dpa99c/react-native-launch-navigator#33]
# Bug report

In the README.md we can find
`options - optional parameters:
{string} app - name of the navigation app to use for directions. Specify using LaunchNavigator.APP constants. e.g. LaunchNavigator.APP.GOOGLE_MAPS. If not specified, defaults to user selection via native picker UI.`

On my android phone I have google maps and waze installed. Both are returned by `LaunchNavigator.getAvailableApps();``

When I request a navigation, I don't have any native picker but instead G. Maps is launched.

**Expected behavior:**

As described in the readme a native picker to choose an app for the navigation (e.g. waze) should pop

**Steps to reproduce:**

- On a android phone, make sure to have gmaps and waze installed
```
LaunchNavigator.navigate(
                    [target.latitude, target.longitude],
                    {
                      start: `${coord.latitude}, ${coord.longitude}`,
                      launchMode: LaunchNavigator.LAUNCH_MODE.TURN_BY_TURN,
                    },
                  )
                    .then(() => console.log('laucnhed'))
                    .catch(err => console.log(err));
```

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
This is a documentation issue:
> If not specified, defaults to user selection via native picker UI

This is not the case for this module (see #8) and has been erroneously carried over from the documentation for [phonegap-launch-navigator](https://github.com/dpa99c/phonegap-launch-navigator) which does provide a native picker UI.
This module currently does not provide an out-of-the-box picker UI so it's up to the app developer to implement a UI with which the user can select their chosen app.
