### ISSUE TITLE
Question: Waze setting BOTH q & ll parameters?

### ISSUE THREAD

**Issue by eranmore** [dpa99c/react-native-launch-navigator#35]
Question: Waze deeplink - 
What is the meaning of setting **both Q & LL** parameters?

For example:
`https://waze.com/ul?q=66%20Acacia%20Avenue&ll=45.6906304,-120.810983&navigate=yes
`vs.
`https://waze.com/ul?ll=45.6906304,-120.810983&navigate=yes
`
Documentation isn't clear about it and it looks like the same behavior.

**Comment by dpa99c** [comment]
`q` is a search query string, `ll` is latitude/longitude pair. 
If you specify both, `ll` takes precedence.
See the [Waze developer docs](https://developers.google.com/waze/deeplinks#urls) for more detail.
