### ISSUE TITLE
iOS getAvailableApps() wrong results

### ISSUE THREAD

**Issue by irodeanu** [dpa99c/react-native-launch-navigator#5]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Environment information**

- React Native version
	- `0.55.3`
- Dev machine OS and version, e.g.
    - OSX
        - `10.14`

_Runtime issue_
- Device details
    - _iPhone 7, iPhone 6_
- OS details
    - _iOS 11.2, iOS 9.3.3_	
	
**Related code:**

```
LaunchNavigator.getAvailableApps()
```

**Console output**

```

{"_40":0,"_65":0,"_55":null,"_72":null}

```

**Comment by dpa99c** [comment]
`getAvailableApps()` is [used by the example app project](https://github.com/dpa99c/react-native-launch-navigator-example/blob/master/app/components/LNAppPicker.js#L25) and appears to return the expected data structure; if I modify the [`console.log()` statement in the example](https://github.com/dpa99c/react-native-launch-navigator-example/blob/master/app/components/LNAppPicker.js#L27) to this:

	console.log("->getAvailableApps(): "+JSON.stringify(apps));

The output I get from an iPhone 7 running iOS 12.1 is this:

	->getAvailableApps(): {"sygic":false,"taxis_99":false,"tomtom":false,"waze":false,"cabify":false,"gaode":false,"citymapper":false,"yandex":false,"here_maps":false,"navigon":false,"lyft":false,"transit_app":false,"maps_me":false,"apple_maps":true,"moovit":false,"uber":false,"baidu":false,"google_maps":false}

Please try building and running the [example app project](https://github.com/dpa99c/react-native-launch-navigator-example) to confirm you get the same results.

**Comment by irodeanu** [comment]
On example project:

`` let apps = LaunchNavigator.getAvailableApps();  ``

`` console.log(JSON.stringify(apps)); ``

Response

`` {"_40":0,"_65":0,"_55":null,"_72":null} ``

**Comment by dpa99c** [comment]
OK, I think I see the problem here: [the documentation for `getAvailableApps()`](https://github.com/dpa99c/react-native-launch-navigator#getavailableapps) is wrong.
It indicates that the result is returned synchronously, but because `getAvailableApps()` is a native module function, the result is returned asynchronously via a Promise.

So try this:


	LaunchNavigator.getAvailableApps()
		.then((apps) => {
		    console.log("->getAvailableApps(): "+JSON.stringify(apps));
		})
		.catch((error) => {
		    console.error(error);
		});

I'll update the documentation to make this clear and check if any other functions are wrongly documented as returning results sychronously.
